// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghkplojtidqvgmjxdnsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoa3Bsb2p0aWRxdmdtanhkbnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxOTg0OTcsImV4cCI6MjA1Mzc3NDQ5N30.mnvsZDpug35L8cb0bAttRu15DANoOnz6sjf09kIUbrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);